/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.math;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.ExternalCall#getFunction <em>Function</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.ExternalCall#getExpressions <em>Expressions</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExternalCall()
 * @model
 * @generated
 */
public interface ExternalCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' reference.
   * @see #setFunction(ExternalDeclaration)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExternalCall_Function()
   * @model
   * @generated
   */
  ExternalDeclaration getFunction();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.ExternalCall#getFunction <em>Function</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(ExternalDeclaration value);

  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.math.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExternalCall_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExpressions();

} // ExternalCall
